# -*- coding: utf-8 -*-
"""telemetry_explorer.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XKdZdNQnZ-eb7ajHJHQkGtsWbVzByOdL
"""

pip install plotly pandas numpy scipy

"""
Hardware Telemetry Anomaly Explorer
=====================================
Simulates multi-signal hardware telemetry (thermal, voltage, power, perf counters)
and builds an interactive multi-axis Plotly dashboard for anomaly exploration.

Run: pip install plotly pandas numpy scipy
Then: python telemetry_explorer.py
"""

import numpy as np
import pandas as pd
import plotly.graph_objects as go
from plotly.subplots import make_subplots
from scipy import stats

# ── 1. Simulate hardware telemetry ──────────────────────────────────────────

np.random.seed(42)
n = 500
t = pd.date_range("2024-01-01", periods=n, freq="100ms")  # 10Hz sensor data

# Base signals with realistic noise
thermal    = 45 + np.cumsum(np.random.randn(n) * 0.3)          # °C — thermal zone
voltage    = 1.8 + np.random.randn(n) * 0.02                    # V  — power rail
power      = 12 + np.random.randn(n) * 0.5 + 0.01 * np.arange(n)  # W — SoC power
perf_score = 100 + np.random.randn(n) * 2                       # AU — PMU perf counter

# Inject anomalies
anomaly_idx = [120, 121, 122, 300, 301, 450]
thermal[120:123]    += 18   # thermal spike
voltage[300:302]    -= 0.15 # voltage droop
perf_score[450]     -= 30   # perf drop

df = pd.DataFrame({
    "time":       t,
    "thermal_C":  thermal,
    "voltage_V":  voltage,
    "power_W":    power,
    "perf_score": perf_score,
})

# ── 2. Feature engineering ───────────────────────────────────────────────────

df["thermal_roc"]    = df["thermal_C"].diff()           # rate-of-change
df["voltage_zscore"] = np.abs(stats.zscore(df["voltage_V"].fillna(0)))
df["power_zscore"]   = np.abs(stats.zscore(df["power_W"].fillna(0)))
df["is_anomaly"]     = (
    (df["thermal_roc"].abs() > 2) |
    (df["voltage_zscore"] > 3)    |
    (df["power_zscore"] > 3)
)

anomalies = df[df["is_anomaly"]]

# ── 3. Build interactive multi-axis Plotly dashboard ─────────────────────────

fig = make_subplots(
    rows=4, cols=1,
    shared_xaxes=True,
    subplot_titles=[
        "Thermal Zone (°C) + Rate-of-Change",
        "Voltage Rail (V) — Z-score Anomaly Detection",
        "SoC Power Draw (W)",
        "PMU Performance Counter",
    ],
    vertical_spacing=0.07,
    row_heights=[0.3, 0.25, 0.25, 0.2],
)

# — Row 1: Thermal + ROC overlay
fig.add_trace(go.Scatter(
    x=df["time"], y=df["thermal_C"],
    name="Thermal (°C)", line=dict(color="#FF6B35", width=1.5)
), row=1, col=1)

fig.add_trace(go.Scatter(
    x=df["time"], y=df["thermal_roc"],
    name="Thermal ROC", line=dict(color="#FFA500", dash="dot", width=1),
    yaxis="y5"  # secondary axis handled via layout below
), row=1, col=1)

# Anomaly markers on thermal
fig.add_trace(go.Scatter(
    x=anomalies["time"], y=anomalies["thermal_C"],
    mode="markers", name="Anomaly",
    marker=dict(color="red", size=8, symbol="x"),
    showlegend=True,
), row=1, col=1)

# — Row 2: Voltage + Z-score band
fig.add_trace(go.Scatter(
    x=df["time"], y=df["voltage_V"],
    name="Voltage (V)", line=dict(color="#4ECDC4", width=1.5)
), row=2, col=1)

# Highlight voltage anomaly windows
for _, row in anomalies[anomalies["voltage_zscore"] > 3].iterrows():
    fig.add_vrect(
        x0=row["time"] - pd.Timedelta("200ms"),
        x1=row["time"] + pd.Timedelta("200ms"),
        fillcolor="red", opacity=0.2, line_width=0,
        row=2, col=1,
    )

# — Row 3: Power draw
fig.add_trace(go.Scatter(
    x=df["time"], y=df["power_W"],
    name="Power (W)", line=dict(color="#45B7D1", width=1.5),
    fill="tozeroy", fillcolor="rgba(69,183,209,0.1)",
), row=3, col=1)

# Rolling average
rolling_power = df["power_W"].rolling(20, center=True).mean()
fig.add_trace(go.Scatter(
    x=df["time"], y=rolling_power,
    name="Power (20-pt avg)", line=dict(color="#0077B6", width=2, dash="dash")
), row=3, col=1)

# — Row 4: Perf counter
fig.add_trace(go.Scatter(
    x=df["time"], y=df["perf_score"],
    name="Perf Score", line=dict(color="#96CEB4", width=1.5)
), row=4, col=1)

# ── 4. Layout & interactivity ─────────────────────────────────────────────────

fig.update_layout(
    title=dict(
        text="Hardware Telemetry Anomaly Explorer — Multi-Axis Time-Series",
        font=dict(size=16)
    ),
    height=900,
    hovermode="x unified",       # unified hover across all subplots
    template="plotly_dark",
    legend=dict(orientation="h", y=-0.05),
    xaxis4=dict(
        rangeslider=dict(visible=True),   # scrubable time range slider
        type="date",
    ),
)

# Axis labels
fig.update_yaxes(title_text="°C", row=1, col=1)
fig.update_yaxes(title_text="Volts", row=2, col=1)
fig.update_yaxes(title_text="Watts", row=3, col=1)
fig.update_yaxes(title_text="AU", row=4, col=1)

fig.show()

# ── 5. Summary stats (print to console) ──────────────────────────────────────

print("\n=== Anomaly Summary ===")
print(f"Total anomalies detected : {df['is_anomaly'].sum()}")
print(f"Thermal spikes (ROC > 2) : {(df['thermal_roc'].abs() > 2).sum()}")
print(f"Voltage droops (z > 3)   : {(df['voltage_zscore'] > 3).sum()}")
print(f"Power anomalies (z > 3)  : {(df['power_zscore'] > 3).sum()}")
print("\n=== Signal Statistics ===")
print(df[["thermal_C","voltage_V","power_W","perf_score"]].describe().round(3))